### ISSUE TITLE
FirewallCluster - VPN - Automatic Site

### ISSUE THREAD

**Issue by Nico059** [Forcepoint/fp-NGFW-SMC-python#64]
Hello,

I would like to disable "Add and update IP addresses based on routing" in vpn sites .
I don't find a function.

Engine -> VPN -> Sites
![2024-11-05_17h07_31](https://github.com/user-attachments/assets/f9afa775-be56-4e46-a1bc-069ac0adf394)

Is it possible to deactivate it in running cluster with smc-python?

Best regards,
Nicolas

**Comment by lilianValeroFp** [comment]
Hi Nicolas, it does not seem supported yet on smc-python lib but in SMC API, you have the "automatic" attribute on site element. So as workaround, I advise you to operate directly with the SMC API with a PUT request in order to update the Site and set its "automatic" attribute to true or false. I will open an issue in order to support it in the next smc-python version.
BR

**Comment by EtienneMILON** [comment]
Hello @lilianValeroFp,

Can you give an example of this PUT request please ?
Can we use `smc.api.common.SMCRequest` ?

Best regards,

**Comment by lilianValeroFp** [comment]
Hi,
I guess something like:
SMCRequest(href=site_uri, json=new_site_payload, headers={"if-match": site_etag}).update()
with new_site_payload containing "automatic":True or False.
And for the site_etag:
site_details = SMCRequest(site_uri).read()
site_etag = site_details.headers["etag"]
BR
